### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by TheDoctorTimeLord** [TheDoctorTimeLord/JEngineGDX#2]
На текущий момент проект выходит из состояния "подготовка к разработки" на состояние "прототипирование".

Сейчас понятно, что вся игра должна делится условно на "сервер" (обработчик всей внутренней логики игры) и "клиент" (всё, что связано с UI). Нужно это для лёгкости внедрения онлайн игры и предотвращения сильного связанния внутренней логики и её отображения. Для глобального проектирования игры используется паттерн MVVM, где Model - тот самый "сервер", View и ViewModel - сам клиент. При этом клиент внутри достаточно сильно связан, однако здесь View - всё что касается рендеринга внутреннего состояния клиента, а ViewModel - адаптер Model для View, а также дополнительная обработка логики клиента.

В проекте решено использовать ECS для организации данных UI. Также рассматривается его использование в модели игры.

Цель текущей стадии сделать прототип UI с помощью ECS и оценить, стоит ли дальше идти таким путём. В результате прототип должен уметь:
 - [ ] Пользовательский ввод
    - [ ] Обрабатывать ввод с клавиатуры
       - [x] Трекинг ввода с клавиатуры
       - [ ] Биндинг клавиш ввода (например, возможность поменять кнопки для перемещения персонажа)
       - [ ] Иерархическая обработка событий ввода
    - [ ] Обрабатывать ввод с мыши
       - [x] Drag and drop
       - [x] Отслеживание действий мыши
       - [ ] Обработка различных видов нажатых клавиш мыши
    - [ ] Иметь возможность расширения на альтернативный ввод
       - [ ] Контроллеры
 - [ ] Рендеринг
    - [x] Производить иерархический рендеринг (от самого дальнего к пользователю объекта к самому ближнему)
    - [x] Иметь возможность расширять способы отрисовки (подсистемы рендеринга)
    - [x] Поддерживать частичный рендеринг (не все объекты сразу, а только необходимые)
    - [ ] Разнообразить способы отрисовки
       - [ ] Анимация
          - [ ] Возможность обработки скелетной анимации
          - [ ] Возможность обработки классической анимации
       - [ ] Частицы
       - [ ] Произвольные полигоны
 - [x] Реагировать на изменения "модели" игры
    - [x] Слушать события модели и применять их в UI
    - [x] Уметь публиковать события в модель
 - [ ] Общая архитектура
    - [x] #5
       - [x] Объекты на текущей сцене определяются специальном компонентом
       - [ ] Возможность выгрузки сущностей, относящихся с конкретной сцене
    - [x] Делить систему по типу обработки:
       - [x]  Последовательная обработка тактов цикла обновления UI
       - [x]  Реакционная обработка на изменения в системе. Поддерживать лёгкость работы ECS при реакционной обработке
    - [x] Возможность загрузки UI из JSON файла
       - [x] Загрузка сущностей из JSON файла
       - [x] Проверка корректности JSON перед загрузкой
          - [x] Проверка валидирования Entity и Prototype
          - [x] Произвольная пользовательская валидация
       - [x] Поддержка дополняемых полей (например, сущность импортирует компоненты родителя и не переопределяет значение со списком, а дописывает свои данные в него).
    - [x] Поддержка сущностей-прототипов (как Archetype, только с данными).
       - [x] Создание отдельных entity по прототипам
       - [x] Создание дочерних сущностей
    - [x] Выделить итоговый список необходимых core систем
       - [x] Давать возможность пользователю библиотеки задавать список систем самостоятельно
       - [x] Давать возможность отключать или включать некоторые системы
    - [ ] Поддержка классической UI схемы (формочки, окна с параметрами, списки и т.д.)
       - [x] Организовать иерархию объектов, составляющих формы и окна
       - [ ] Научиться делать обработку компонентов форм и окон
          - [ ] Вывод полей формы
          - [x] Поддержка отдельных сущностей внутри формы (список перетаскиваемых объектов)
          - [x] Шапка формы/окна
             - [x] Перетаскивание всей формы/окна по экрану с помощью зажатия ЛКП по шапке
             - [x] Кнопки действия с формой/окном (например, закрыть форму/окно)
          - [x] Поддержка кастомных настроек содержимого формы
          - [x] Поддержка кастомной обработки результата работы с формой
 - [ ] Расширение логики UI
    - [x] Давать возможность валидирования (поддержания консистентности) компонентной модели UI, позволяя пересчитывать некоторые данный в момент их изменения
    - [ ] Давать возможность некоторую логику игры производить в UI части
